services:
  php:
    build:
      context: ./php
    container_name: berapaya_php
    healthcheck:
      test: ["CMD-SHELL", "php artisan --version"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./src:/var/www/html
    environment:
      - PROJECT_NAME=berapaya
    depends_on:
      - db
    networks:
      - default
      - shared_net

  nginx:
    build:
      context: ./nginx
    container_name: berapaya_nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -k -fsSL https://berapaya.test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php
    networks:
      - default
      - shared_net

  db:
    image: mariadb:10.11
    container_name: berapaya_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: berapaya
      MYSQL_ROOT_PASSWORD: p455w0rd
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    networks:
      - default
      - shared_net
      
networks:
  default:
    driver: bridge
  shared_net:
    external: true
